" Basics
  syntax on
  set number
  set laststatus=2
  set ruler
  set cursorline
  set showmode
  set nowrap

" Colours
  colorscheme Tomorrow-Night

" Tabs and whitespace
  set expandtab
  set tabstop=2
  set shiftwidth=2
  set smartindent

" Searching
  set hlsearch
  set incsearch
  set ignorecase

" Filetypes
   au BufNewFile,BufRead Vagrantfile set filetype=ruby
   au BufNewFile,BufRead Gemfile set filetype=ruby

" Paste
  set clipboard=unnamed
