" Pathogen
  execute pathogen#infect()

" Basics
  syntax on
  set number
  set laststatus=2
  set ruler
  set showmode
  set cursorline
  set wildmenu
  set nowrap
  set wildmenu

" Enable filetype plugins
  filetype plugin on

" Colours
  colorscheme base16-oceanicnext

" All the backspaces!
  set backspace=indent,eol,start

" Centralize backups, swapfiles and undo history
  set backupdir=~/.vim/backups
  set directory=~/.vim/swaps

" Tabs and whitespace
  set expandtab
  set tabstop=2
  set shiftwidth=2
  set smartindent

" Searching
  set hlsearch
  set incsearch
  set ignorecase

" Filetypes
  au BufNewFile,BufRead Vagrantfile set filetype=ruby
  au BufNewFile,BufRead Gemfile set filetype=ruby

" Paste
  set clipboard=unnamed

" nerdtree
  map <C-n> :NERDTreeToggle<CR>

" JSX syntax
  let g:jsx_ext_required = 0

" ctrlp
  let g:ctrlp_custom_ignore = '\v[\/](\.(git|hg|svn)|node_modules)$'

" prettier
  autocmd FileType javascript setlocal formatprg=prettier\ --stdin\ --single-quote 
  let g:neoformat_try_formatprg = 1

" vim-go
  let g:go_fmt_command = "goimports"
