# prompt
autoload -U promptinit && promptinit
prompt pure

# git auto-complete
autoload -Uz compinit && compinit

# fix delete in terminal
bindkey "^[[3~" delete-char

# history
export HISTSIZE=100000
export SAVEHIST=$HISTSIZE
export HISTFILE=~/.zsh_history

# aliases
alias gcb="git rev-parse --abbrev-ref HEAD"
alias gp='git push'
alias gpl='git pull'
alias ll='ls -lh'
alias nodemon='NODE_ENV=dev nodemon -e html,js,json'
alias reload='source ~/.zshrc'

# environment
export CLICOLOR=1
export GREP_OPTIONS='--color=auto'
export EDITOR='/usr/local/bin/vim'
export PATH=$PATH:~/bin

# ruby
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby ruby

# go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

s () {
  [[ -f "$1" ]] && source "$1"
}

# overrides
s ~/.secrets
s ~/.overrides
